---
kind: pipeline
type: docker
name: default

services:
  - name: bitcoind
    image: coinzway/bitcoind-integration-test-docker:0.19.0.1
  - name: litecoind
    image: coinzway/litecoind-integration-test-docker:0.17.1
  - name: dogecoind
    image: coinzway/dogecoind-integration-test-docker:1.14.2
  - name: dashd
    image: coinzway/dashd-integration-test-docker:0.15.0
  - name: bitcoind_cash
    image: coinzway/bitcoind-cash-integration-test-docker:0.21.0
  - name: zcashd
    image: coinzway/zcashd-integration-test-docker:2.1.1
steps:
  - name: build
    image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    commands:
      - sbt compileAll
  - name: check_scalafmt
    image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    commands:
      - sbt scalafmtCheckAll
  - name: test
    image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    commands:
      - sbt test
  - name: integration_bitcoind
    image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    commands:
      - sbt "project bitcoind" it:test
    depends_on: [ test ]
  - name: integration_litecoind
    image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    commands:
      - sbt "project litecoind" it:test
    depends_on: [ test ]
  - name: integration_dogecoind
    image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    commands:
      - sbt "project dogecoind" it:test
    depends_on: [ test ]
  - name: integration_dashd
    image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    commands:
      - sbt "project dashd" it:test
    depends_on: [ test ]
  - name: integration_bitcoind_cash
    image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    commands:
      - sbt "project bitcoindCash" it:test
    depends_on: [ test ]
  - name: integration_zcashd
    image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    commands:
      - sbt "project zcashd" it:test
    depends_on: [ test ]